# Generated by Django 5.0.14 on 2026-10-09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=10)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('role', models.CharField(default='CUSTOMER', max_length=20)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'otp_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
